logging:
  level:
    ROOT: DEBUG
    com.greengoldfish: DEBUG
spring:
  application:
    name: GreenGoldfish
  datasource:
    url: jdbc:mysql://localhost:3306/green-goldfish?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: green-goldfish
    password: green-goldfish
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    contexts: dev, faker
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
