version: '3.8'
services:
  green-goldfish:
    image: arm64v8/mysql:oracle
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=green-goldfish
      - MYSQL_USER=green-goldfish
      - MYSQL_ROOT_PASSWORD=green-goldfish
      - MYSQL_PASSWORD=green-goldfish
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
